#!/bin/bash

#========================================================
# Android Demo Build and Install Script (build.sh)
# Runs in the project root directory.
# Requires: Java Development Kit (JDK), Gradle Wrapper (./gradlew), and Android Debug Bridge (adb)
#========================================================

# --- Configuration ---
# Path to the Android project root (where build.gradle is)
PROJECT_ROOT="./"
# The task to build the debug APK
BUILD_TASK="assembleDebug"
# The name of the APK file generated by assembleDebug
APK_NAME="app/build/outputs/apk/debug/app-debug.apk"

echo "========================================"
echo "🚀 Starting Android Demo Build Process"
echo "========================================"

# 1. Check for prerequisites
if ! command -v ./gradlew &> /dev/null
then
    echo "❌ Error: Gradle Wrapper (./gradlew) not found in the current directory."
    echo "Please ensure you run this script from the project root."
    exit 1
fi

if ! command -v adb &> /dev/null
then
    echo "❌ Error: Android Debug Bridge (adb) not found in PATH."
    echo "Please ensure 'adb' is installed and accessible in your terminal environment."
    exit 1
fi

# 2. Build the project
echo ""
echo "========================================"
echo "🔨 Step 1: Building the Android Application (Running: ./gradlew $BUILD_TASK)"
echo "========================================"
./gradlew "$BUILD_TASK"

# Check the exit status of the Gradle build command
if [ $? -ne 0 ]; then
    echo ""
    echo "========================================"
    echo "🛑 Build FAILED!"
    echo "========================================"
    echo "Gradle build failed. Check the output above for compilation errors."
    exit 1
fi

echo ""
echo "✅ Build successful! APK generated."

# 3. Check for the APK file
if [ -f "$PROJECT_ROOT/$APK_NAME" ]; then
    echo "🔎 Found APK: $APK_NAME"
else
    echo "❌ Error: APK file '$APK_NAME' was not found after the build."
    echo "Please check the build output path."
    exit 1
fi

# 4. Install the APK
echo ""
echo "========================================"
echo "📱 Step 2: Installing Application on Connected Device/Emulator (Running: adb install $APK_NAME)"
echo "========================================"
adb install "$APK_NAME"

# Check the exit status of the adb install command
if [ $? -eq 0 ]; then
    echo ""
    echo "========================================"
    echo "🎉 SUCCESS! Application installed successfully."
    echo "You should now see the Counter Demo running on your device/emulator."
    echo "========================================"
else
    echo ""
    echo "========================================"
    echo "⚠️ Warning: APK installation might have failed."
    echo "========================================"
    echo "Check if an emulator is running or a physical device is connected and authorized."
    exit 1
fi
